spring:
  application:
    name: chefe-api
  spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/chefe-teste?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    spring:
      servlet:
        multipart:
          max-file-size: 5MB
          max-request-size: 5MB

jwt:
  key: ${JWT_KEY:t02*KcAPVJC1bmCWAArQd1vyUKZkcY7w@v@d@bn^8#*J4MG3$1GQqdDS$NIWMITDKip3j!T2WdBHBesRRKTzqgMgi73ZG#HVLig6KPAvlGtKC%tvgItjHhTY$dOw15levmDR9^0U2juYuW*26LYuYsZ#e6$*@Bj9nPi6$8!3V0kf%O8@n^4r$U^bjm@91YOdsRK2dob@op&eoiGv$EfLOTK4H6n2@I3Jr3Z%PLgnIy19r$hz!%d4XimcD%TXJD8n#unH8DR5NyEj8bT3U@TX$tEECjmz5szGl1$RUFIXPwqCB5MI6*DqV1GQ%fnhEjtOxzEztNGWdRp#A0gdiJzS9R1A}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:den5qbowg}
  api-key: ${CLOUDINARY_API_KEY:297566688675923}
  api-secret: ${CLOUDINARY_API_SECRET:QmXuQt3e0fbknqF95cenGn1ijhs}