spring.application.name=chefe-api
spring.datasource.url=jdbc:h2:mem:dbtestes
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.username=sa
spring.datasource.password=
